
import re
import string

# File organization:
#   Dictionaries
#   Regexes

corporate_standardization_dict = {
    
    "corporation":"corp",
    "corporations":"corps",
    "incorporated":"inc",
    "company":"co",
    "companies":"cos",
    "limited":"ltd",
    "lmtd":"ltd",
    "limited liability corporation":"llc",
    "lmtd liability corporation":"llc",
    "ltd liability corporation":"llc",
    "l liability corporation":"llc",
    "limited l corporation":"llc",
    "lmtd l corporation":"llc",
    "ltd l corporation":"llc",
    "l l corporation":"llc",
    "ll corporation":"llc",
    "limited liability corp":"llc",
    "lmtd liability corp":"llc",
    "ltd liability corp":"llc",
    "l liability corp":"llc",
    "limited l corp":"llc",
    "lmtd l corp":"llc",
    "ltd l corp":"llc",
    "ltd l corp":"llc",
    "l l corp":"llc",
    "ll corp":"llc",
    "limited liability c":"llc",
    "lmtd liability c":"llc",
    "ltd liability c":"llc",
    "l liability c":"llc",
    "limited l c":"llc",
    "lmtd l c":"llc",
    "ltd l c":"llc",
    "l l c":"llc",
    "ll c":"llc",
    "l lc":"llc",
    "limited liability partnership":"llp",
    "lmtd liability partnership":"llp",
    "ltd liability partnership":"llp",
    "l liability partnership":"llp",
    "limited l partnership":"llp",
    "lmtd l partnership":"llp",
    "ltd l partnership":"llp",
    "l l partnership":"llp",
    "ll partnership":"llp",
    "limited liability part":"llp",
    "lmtd liability part":"llp",
    "ltd liability part":"llp",
    "l liability part":"llp",
    "limited l part":"llp",
    "lmtd l part":"llp",
    "ltd l part":"llp",
    "ltd l part":"llp",
    "l l part":"llp",
    "ll part":"llp",
    "limited liability ptnr":"llp",
    "lmtd liability ptnr":"llp",
    "ltd liability ptnr":"llp",
    "l liability ptnr":"llp",
    "limited l ptnr":"llp",
    "lmtd l ptnr":"llp",
    "ltd l ptnr":"llp",
    "ltd l ptnr":"llp",
    "l l ptnr":"llp",
    "ll ptnr":"llp",
    "limited liability p":"llp",
    "lmtd liability p":"llp",
    "ltd liability p":"llp",
    "l liability p":"llp",
    "limited l p":"llp",
    "lmtd l p":"llp",
    "ltd l p":"llp",
    "l l p":"llp",
    "ll p":"llp",
    "l lp":"llp",

    "hldg":"holding",
    "hldgs":"holdings", # consider also ading acquisitions
    "sp":"special",
    "mtl":"mutual",
    "coop":"cooperative",
    "co op":"cooperative",
    "co-op":"cooperative",

    "mtg":"mortgage",
    "mort":"mortgage",
    "mtge":"mortgage",
    "mrtg":"mortgage",
    "mortg":"mortgage",
    "mortge":"mortgage",
    "ins":"insurance",
    "sb":"savings bank",
    "bk":"bank",
    "bks":"banks",
    "bkg":"banking",
    "msb":"money service business",
    "te":"trustee",
    "tr":"trust",
    "tc":"trust",
    "ln":"loan",
    "lns":"loans",
    "lnd":"lend",
    "fndg":"funding",
    "fin":"financial",
    "fncl":"financial",
    "svg":"savings",
    "inv":"investment",
    "br":"branch",
    "b & t":"bank and trust",
    "b&t":"bank and trust",
    "b and t":"bank and trust",
    "cap":"capital",
    "svc":"service",
    "plc":"place",

    # Federal credit unions
    "federal credit union":"fcu",
    "fedl credit union":"fcu",
    "fed credit union":"fcu",
    "f credit union":"fcu",
    "federal cred union":"fcu",
    "fedl cred union":"fcu",
    "fed cred union":"fcu",
    "f cred union":"fcu",
    "federal c union":"fcu",
    "fedl c union":"fcu",
    "fed c union":"fcu",
    "f c union":"fcu",
    "federal credit u":"fcu",
    "fedl credit u":"fcu",
    "fed credit u":"fcu",
    "f credit u":"fcu",
    "federal cred u":"fcu",
    "fedl cred u":"fcu",
    "fed cred u":"fcu",
    "f cred u":"fcu",
    "federal c u":"fcu",
    "fedl c u":"fcu",
    "fed c u":"fcu",
    "f c u":"fcu",

    # FNMA/Fannie Mae
    "federal national mortgage association":"fnma",
    "fed national mortgage association":"fnma",
    "f national mortgage association":"fnma",
    "federal natl mortgage association":"fnma",
    "fedl natl mortgage association":"fnma",
    "fed natl mortgage association":"fnma",
    "f natl mortgage association":"fnma",
    "federal nat mortgage association":"fnma",
    "fedl nat mortgage association":"fnma",
    "fed nat mortgage association":"fnma",
    "f nat mortgage association":"fnma",
    "federal n mortgage association":"fnma",
    "fedl n mortgage association":"fnma",
    "fed n mortgage association":"fnma",
    "f n mortgage association":"fnma",
    "federal national mtg association":"fnma",
    "fedl national mtg association":"fnma",
    "fed national mtg association":"fnma",
    "f national mtg association":"fnma",
    "federal natl mtg association":"fnma",
    "fedl natl mtg association":"fnma",
    "fed natl mtg association":"fnma",
    "f natl mtg association":"fnma",
    "federal nat mtg association":"fnma",
    "fedl nat mtg association":"fnma",
    "fed nat mtg association":"fnma",
    "f nat mtg association":"fnma",
    "federal n mtg association":"fnma",
    "fedl n mtg association":"fnma",
    "fed n mtg association":"fnma",
    "f n mtg association":"fnma",
    "federal national mtge association":"fnma",
    "fedl national mtge association":"fnma",
    "fed national mtge association":"fnma",
    "f national mtge association":"fnma",
    "federal natl mtge association":"fnma",
    "fedl natl mtge association":"fnma",
    "fed natl mtge association":"fnma",
    "f natl mtge association":"fnma",
    "federal nat mtge association":"fnma",
    "fedl nat mtge association":"fnma",
    "fed nat mtge association":"fnma",
    "f nat mtge association":"fnma",
    "federal n mtge association":"fnma",
    "fedl n mtge association":"fnma",
    "fed n mtge association":"fnma",
    "f n mtge association":"fnma",
    "federal national m association":"fnma",
    "fedl national m association":"fnma",
    "fed national m association":"fnma",
    "f national m association":"fnma",
    "federal natl m association":"fnma",
    "fedl natl m association":"fnma",
    "fed natl m association":"fnma",
    "f natl m association":"fnma",
    "federal nat m association":"fnma",
    "fedl nat m association":"fnma",
    "fed nat m association":"fnma",
    "f nat m association":"fnma",
    "federal n m association":"fnma",
    "fedl n m association":"fnma",
    "fed n m association":"fnma",
    "f n m association":"fnma",
    "federal national mortgage assoc":"fnma",
    "fedl national mortgage assoc":"fnma",
    "fed national mortgage assoc":"fnma",
    "f national mortgage assoc":"fnma",
    "federal natl mortgage assoc":"fnma",
    "fedl natl mortgage assoc":"fnma",
    "fed natl mortgage assoc":"fnma",
    "f natl mortgage assoc":"fnma",
    "federal nat mortgage assoc":"fnma",
    "fedl nat mortgage assoc":"fnma",
    "fed nat mortgage assoc":"fnma",
    "f nat mortgage assoc":"fnma",
    "federal n mortgage assoc":"fnma",
    "fedl n mortgage assoc":"fnma",
    "fed n mortgage assoc":"fnma",
    "f n mortgage assoc":"fnma",
    "federal national mtg assoc":"fnma",
    "fedl national mtg assoc":"fnma",
    "fed national mtg assoc":"fnma",
    "f national mtg assoc":"fnma",
    "federal natl mtg assoc":"fnma",
    "fedl natl mtg assoc":"fnma",
    "fed natl mtg assoc":"fnma",
    "f natl mtg assoc":"fnma",
    "federal nat mtg assoc":"fnma",
    "fedl nat mtg assoc":"fnma",
    "fed nat mtg assoc":"fnma",
    "f nat mtg assoc":"fnma",
    "federal n mtg assoc":"fnma",
    "fedl n mtg assoc":"fnma",
    "fed n mtg assoc":"fnma",
    "f n mtg assoc":"fnma",
    "federal national mtge assoc":"fnma",
    "fedl national mtge assoc":"fnma",
    "fed national mtge assoc":"fnma",
    "f national mtge assoc":"fnma",
    "federal natl mtge assoc":"fnma",
    "fedl natl mtge assoc":"fnma",
    "fed natl mtge assoc":"fnma",
    "f natl mtge assoc":"fnma",
    "federal nat mtge assoc":"fnma",
    "fedl nat mtge assoc":"fnma",
    "fed nat mtge assoc":"fnma",
    "f nat mtge assoc":"fnma",
    "federal n mtge assoc":"fnma",
    "fedl nat mtge assoc":"fnma",
    "fed nat mtge assoc":"fnma",
    "f n mtge assoc":"fnma",
    "federal national m assoc":"fnma",
    "fedl national m assoc":"fnma",
    "fed national m assoc":"fnma",
    "f national m assoc":"fnma",
    "federal natl m assoc":"fnma",
    "fedl natl m assoc":"fnma",
    "fed natl m assoc":"fnma",
    "f natl m assoc":"fnma",
    "federal nat m assoc":"fnma",
    "fedl nat m assoc":"fnma",
    "fed nat m assoc":"fnma",
    "f nat m assoc":"fnma",
    "federal n m assoc":"fnma",
    "fedl n m assoc":"fnma",
    "fed n m assoc":"fnma",
    "f n m assoc":"fnma",
    "federal national mortgage assn":"fnma",
    "fedl national mortgage assn":"fnma",
    "fed national mortgage assn":"fnma",
    "f national mortgage assn":"fnma",
    "federal natl mortgage assn":"fnma",
    "fedl natl mortgage assn":"fnma",
    "fed natl mortgage assn":"fnma",
    "f natl mortgage assn":"fnma",
    "federal nat mortgage assn":"fnma",
    "fedl nat mortgage assn":"fnma",
    "fed nat mortgage assn":"fnma",
    "f nat mortgage assn":"fnma",
    "federal n mortgage assn":"fnma",
    "fedl n mortgage assn":"fnma",
    "fed n mortgage assn":"fnma",
    "f n mortgage assn":"fnma",
    "federal national mtg assn":"fnma",
    "fedl national mtg assn":"fnma",
    "fed national mtg assn":"fnma",
    "f national mtg assn":"fnma",
    "federal natl mtg assn":"fnma",
    "fedl natl mtg assn":"fnma",
    "fed natl mtg assn":"fnma",
    "f natl mtg assn":"fnma",
    "federal nat mtg assn":"fnma",
    "fedl nat mtg assn":"fnma",
    "fed nat mtg assn":"fnma",
    "f nat mtg assn":"fnma",
    "federal n mtg assn":"fnma",
    "fedl n mtg assn":"fnma",
    "fed n mtg assn":"fnma",
    "f n mtg assn":"fnma",
    "federal national mtge assn":"fnma",
    "fedl national mtge assn":"fnma",
    "fed national mtge assn":"fnma",
    "f national mtge assn":"fnma",
    "federal natl mtge assn":"fnma",
    "fedl natl mtge assn":"fnma",
    "fed natl mtge assn":"fnma",
    "f natl mtge assn":"fnma",
    "federal nat mtge assn":"fnma",
    "fedl nat mtge assn":"fnma",
    "fed nat mtge assn":"fnma",
    "f nat mtge assn":"fnma",
    "federal n mtge assn":"fnma",
    "fedl n mtge assn":"fnma",
    "fed n mtge assn":"fnma",
    "f n mtge assn":"fnma",
    "federal national m assn":"fnma",
    "fedl national m assn":"fnma",
    "fed national m assn":"fnma",
    "f national m assn":"fnma",
    "federal natl m assn":"fnma",
    "fedl natl m assn":"fnma",
    "fed natl m assn":"fnma",
    "f natl m assn":"fnma",
    "federal nat m assn":"fnma",
    "fedl nat m assn":"fnma",
    "fed nat m assn":"fnma",
    "f nat m assn":"fnma",
    "federal n m assn":"fnma",
    "fedl n m assn":"fnma",
    "fed n m assn":"fnma",
    "f n m assn":"fnma",
    "federal national mortgage a":"fnma",
    "fedl national mortgage a":"fnma",
    "fed national mortgage a":"fnma",
    "f national mortgage a":"fnma",
    "federal natl mortgage a":"fnma",
    "fedl natl mortgage a":"fnma",
    "fed natl mortgage a":"fnma",
    "f natl mortgage a":"fnma",
    "federal nat mortgage a":"fnma",
    "fedl nat mortgage a":"fnma",
    "fed nat mortgage a":"fnma",
    "f nat mortgage a":"fnma",
    "federal n mortgage a":"fnma",
    "fedl n mortgage a":"fnma",
    "fed n mortgage a":"fnma",
    "f n mortgage a":"fnma",
    "federal national mtg a":"fnma",
    "fedl national mtg a":"fnma",
    "fed national mtg a":"fnma",
    "f national mtg a":"fnma",
    "federal natl mtg a":"fnma",
    "fedl natl mtg a":"fnma",
    "fed natl mtg a":"fnma",
    "f natl mtg a":"fnma",
    "federal nat mtg a":"fnma",
    "fedl nat mtg a":"fnma",
    "fed nat mtg a":"fnma",
    "f nat mtg a":"fnma",
    "federal n mtg a":"fnma",
    "fedl n mtg a":"fnma",
    "fed n mtg a":"fnma",
    "f n mtg a":"fnma",
    "federal national mtge a":"fnma",
    "fedl national mtge a":"fnma",
    "fed national mtge a":"fnma",
    "f national mtge a":"fnma",
    "federal natl mtge a":"fnma",
    "fedl natl mtge a":"fnma",
    "fed natl mtge a":"fnma",
    "f natl mtge a":"fnma",
    "federal nat mtge a":"fnma",
    "fedl nat mtge a":"fnma",
    "fed nat mtge a":"fnma",
    "f nat mtge a":"fnma",
    "federal n mtge a":"fnma",
    "fedl n mtge a":"fnma",
    "fed n mtge a":"fnma",
    "f n mtge a":"fnma",
    "federal national m a":"fnma",
    "fedl national m a":"fnma",
    "fed national m a":"fnma",
    "f national m a":"fnma",
    "federal natl m a":"fnma",
    "fedl natl m a":"fnma",
    "fed natl m a":"fnma",
    "f natl m a":"fnma",
    "federal nat m a":"fnma",
    "fedl nat m a":"fnma",
    "fed nat m a":"fnma",
    "f nat m a":"fnma",
    "federal n m a":"fnma",
    "fedl n m a":"fnma",
    "fed n m a":"fnma",
    "f n m a":"fnma",
    "fannie mae":"fnma",
    "fan mae":"fnma",

    # FHLMC / Freddie Mac
    "federal home loan mortgage corporation":"fhlmc",
    "fedl home loan mortgage corporation":"fhlmc",
    "fed home loan mortgage corporation":"fhlmc",
    "f home loan mortgage corporation":"fhlmc",
    "federal hm loan mortgage corporation":"fhlmc",
    "fedl hm loan mortgage corporation":"fhlmc",
    "fed hm loan mortgage corporation":"fhlmc",
    "f hm loan mortgage corporation":"fhlmc",
    "federal h loan mortgage corporation":"fhlmc",
    "fedl h loan mortgage corporation":"fhlmc",
    "fed h loan mortgage corporation":"fhlmc",
    "f h loan mortgage corporation":"fhlmc",
    "federal home ln mortgage corporation":"fhlmc",
    "fedl home ln mortgage corporation":"fhlmc",
    "fed home ln mortgage corporation":"fhlmc",
    "f home ln mortgage corporation":"fhlmc",
    "federal hm ln mortgage corporation":"fhlmc",
    "fedl hm ln mortgage corporation":"fhlmc",
    "fed hm ln mortgage corporation":"fhlmc",
    "f hm ln mortgage corporation":"fhlmc",
    "federal h ln mortgage corporation":"fhlmc",
    "fedl h ln mortgage corporation":"fhlmc",
    "fed h ln mortgage corporation":"fhlmc",
    "f h ln mortgage corporation":"fhlmc",
    "federal home l mortgage corporation":"fhlmc",
    "fedl home l mortgage corporation":"fhlmc",
    "fed home l mortgage corporation":"fhlmc",
    "f home l mortgage corporation":"fhlmc",
    "federal hm l mortgage corporation":"fhlmc",
    "fedl hm l mortgage corporation":"fhlmc",
    "fed hm l mortgage corporation":"fhlmc",
    "f hm l mortgage corporation":"fhlmc",
    "federal h l mortgage corporation":"fhlmc",
    "fedl h l mortgage corporation":"fhlmc",
    "fed h l mortgage corporation":"fhlmc",
    "f h l mortgage corporation":"fhlmc",
    "federal home loan mtge corporation":"fhlmc",
    "fedl home loan mtge corporation":"fhlmc",
    "fed home loan mtge corporation":"fhlmc",
    "f home loan mtge corporation":"fhlmc",
    "federal hm loan mtge corporation":"fhlmc",
    "fedl hm loan mtge corporation":"fhlmc",
    "fed hm loan mtge corporation":"fhlmc",
    "f hm loan mtge corporation":"fhlmc",
    "federal h loan mtge corporation":"fhlmc",
    "fedl h loan mtge corporation":"fhlmc",
    "fed h loan mtge corporation":"fhlmc",
    "f h loan mtge corporation":"fhlmc",
    "federal home ln mtge corporation":"fhlmc",
    "fedl home ln mtge corporation":"fhlmc",
    "fed home ln mtge corporation":"fhlmc",
    "f home ln mtge corporation":"fhlmc",
    "federal hm ln mtge corporation":"fhlmc",
    "fedl hm ln mtge corporation":"fhlmc",
    "fed hm ln mtge corporation":"fhlmc",
    "f hm ln mtge corporation":"fhlmc",
    "federal h ln mtge corporation":"fhlmc",
    "fedl h ln mtge corporation":"fhlmc",
    "fed h ln mtge corporation":"fhlmc",
    "f h ln mtge corporation":"fhlmc",
    "federal home l mtge corporation":"fhlmc",
    "fedl home l mtge corporation":"fhlmc",
    "fed home l mtge corporation":"fhlmc",
    "f home l mtge corporation":"fhlmc",
    "federal hm l mtge corporation":"fhlmc",
    "fedl hm l mtge corporation":"fhlmc",
    "fed hm l mtge corporation":"fhlmc",
    "f hm l mtge corporation":"fhlmc",
    "federal h l mtge corporation":"fhlmc",
    "fedl h l mtge corporation":"fhlmc",
    "fed h l mtge corporation":"fhlmc",
    "f h l mtge corporation":"fhlmc",
    "federal home loan mtg corporation":"fhlmc",
    "fedl home loan mtg corporation":"fhlmc",
    "fed home loan mtg corporation":"fhlmc",
    "f home loan mtg corporation":"fhlmc",
    "federal hm loan mtg corporation":"fhlmc",
    "fedl hm loan mtg corporation":"fhlmc",
    "fed hm loan mtg corporation":"fhlmc",
    "f hm loan mtg corporation":"fhlmc",
    "federal h loan mtg corporation":"fhlmc",
    "fedl h loan mtg corporation":"fhlmc",
    "fed h loan mtg corporation":"fhlmc",
    "f h loan mtg corporation":"fhlmc",
    "federal home ln mtg corporation":"fhlmc",
    "fedl home ln mtg corporation":"fhlmc",
    "fed home ln mtg corporation":"fhlmc",
    "f home ln mtg corporation":"fhlmc",
    "federal hm ln mtg corporation":"fhlmc",
    "fedl hm ln mtg corporation":"fhlmc",
    "fed hm ln mtg corporation":"fhlmc",
    "f hm ln mtg corporation":"fhlmc",
    "federal h ln mtg corporation":"fhlmc",
    "fedl h ln mtg corporation":"fhlmc",
    "fed h ln mtg corporation":"fhlmc",
    "f h ln mtg corporation":"fhlmc",
    "federal home l mtg corporation":"fhlmc",
    "fedl home l mtg corporation":"fhlmc",
    "fed home l mtg corporation":"fhlmc",
    "f home l mtg corporation":"fhlmc",
    "federal hm l mtg corporation":"fhlmc",
    "fedl hm l mtg corporation":"fhlmc",
    "fed hm l mtg corporation":"fhlmc",
    "f hm l mtg corporation":"fhlmc",
    "federal h l mtg corporation":"fhlmc",
    "fedl h l mtg corporation":"fhlmc",
    "fed h l mtg corporation":"fhlmc",
    "f h l mtg corporation":"fhlmc",
    "federal home loan m corporation":"fhlmc",
    "fedl home loan m corporation":"fhlmc",
    "fed home loan m corporation":"fhlmc",
    "f home loan m corporation":"fhlmc",
    "federal hm loan m corporation":"fhlmc",
    "fedl hm loan m corporation":"fhlmc",
    "fed hm loan m corporation":"fhlmc",
    "f hm loan m corporation":"fhlmc",
    "federal h loan m corporation":"fhlmc",
    "fedl h loan m corporation":"fhlmc",
    "fed h loan m corporation":"fhlmc",
    "f h loan m corporation":"fhlmc",
    "federal home ln m corporation":"fhlmc",
    "fedl home ln m corporation":"fhlmc",
    "fed home ln m corporation":"fhlmc",
    "f home ln m corporation":"fhlmc",
    "federal hm ln m corporation":"fhlmc",
    "fedl hm ln m corporation":"fhlmc",
    "fed hm ln m corporation":"fhlmc",
    "f hm ln m corporation":"fhlmc",
    "federal h ln m corporation":"fhlmc",
    "fedl h ln m corporation":"fhlmc",
    "fed h ln m corporation":"fhlmc",
    "f h ln m corporation":"fhlmc",
    "federal home l m corporation":"fhlmc",
    "fedl home l m corporation":"fhlmc",
    "fed home l m corporation":"fhlmc",
    "f home l m corporation":"fhlmc",
    "federal hm l m corporation":"fhlmc",
    "fedl hm l m corporation":"fhlmc",
    "fed hm l m corporation":"fhlmc",
    "f hm l m corporation":"fhlmc",
    "federal h l m corporation":"fhlmc",
    "fedl h l m corporation":"fhlmc",
    "fed h l m corporation":"fhlmc",
    "f h l m corporation":"fhlmc",
    "federal home loan mortgage corp":"fhlmc",
    "fedl home loan mortgage corp":"fhlmc",
    "fed home loan mortgage corp":"fhlmc",
    "f home loan mortgage corp":"fhlmc",
    "federal hm loan mortgage corp":"fhlmc",
    "fedl hm loan mortgage corp":"fhlmc",
    "fed hm loan mortgage corp":"fhlmc",
    "f hm loan mortgage corp":"fhlmc",
    "federal h loan mortgage corp":"fhlmc",
    "fedl h loan mortgage corp":"fhlmc",
    "fed h loan mortgage corp":"fhlmc",
    "f h loan mortgage corp":"fhlmc",
    "federal home ln mortgage corp":"fhlmc",
    "fedl home ln mortgage corp":"fhlmc",
    "fed home ln mortgage corp":"fhlmc",
    "f home ln mortgage corp":"fhlmc",
    "federal hm ln mortgage corp":"fhlmc",
    "fedl hm ln mortgage corp":"fhlmc",
    "fed hm ln mortgage corp":"fhlmc",
    "f hm ln mortgage corp":"fhlmc",
    "federal h ln mortgage corp":"fhlmc",
    "fedl h ln mortgage corp":"fhlmc",
    "fed h ln mortgage corp":"fhlmc",
    "f h ln mortgage corp":"fhlmc",
    "federal home l mortgage corp":"fhlmc",
    "fedl home l mortgage corp":"fhlmc",
    "fed home l mortgage corp":"fhlmc",
    "f home l mortgage corp":"fhlmc",
    "federal hm l mortgage corp":"fhlmc",
    "fedl hm l mortgage corp":"fhlmc",
    "fed hm l mortgage corp":"fhlmc",
    "f hm l mortgage corp":"fhlmc",
    "federal h l mortgage corp":"fhlmc",
    "fedl h l mortgage corp":"fhlmc",
    "fed h l mortgage corp":"fhlmc",
    "f h l mortgage corp":"fhlmc",
    "federal home loan mtge corp":"fhlmc",
    "fedl home loan mtge corp":"fhlmc",
    "fed home loan mtge corp":"fhlmc",
    "f home loan mtge corp":"fhlmc",
    "federal hm loan mtge corp":"fhlmc",
    "fedl hm loan mtge corp":"fhlmc",
    "fed hm loan mtge corp":"fhlmc",
    "f hm loan mtge corp":"fhlmc",
    "federal h loan mtge corp":"fhlmc",
    "fedl h loan mtge corp":"fhlmc",
    "fed h loan mtge corp":"fhlmc",
    "f h loan mtge corp":"fhlmc",
    "federal home ln mtge corp":"fhlmc",
    "fedl home ln mtge corp":"fhlmc",
    "fed home ln mtge corp":"fhlmc",
    "f home ln mtge corp":"fhlmc",
    "federal hm ln mtge corp":"fhlmc",
    "fedl hm ln mtge corp":"fhlmc",
    "fed hm ln mtge corp":"fhlmc",
    "f hm ln mtge corp":"fhlmc",
    "federal h ln mtge corp":"fhlmc",
    "fedl h ln mtge corp":"fhlmc",
    "fed h ln mtge corp":"fhlmc",
    "f h ln mtge corp":"fhlmc",
    "federal home l mtge corp":"fhlmc",
    "fedl home l mtge corp":"fhlmc",
    "fed home l mtge corp":"fhlmc",
    "f home l mtge corp":"fhlmc",
    "federal hm l mtge corp":"fhlmc",
    "fedl hm l mtge corp":"fhlmc",
    "fed hm l mtge corp":"fhlmc",
    "f hm l mtge corp":"fhlmc",
    "federal h l mtge corp":"fhlmc",
    "fedl h l mtge corp":"fhlmc",
    "fed h l mtge corp":"fhlmc",
    "f h l mtge corp":"fhlmc",
    "federal home loan mtg corp":"fhlmc",
    "fedl home loan mtg corp":"fhlmc",
    "fed home loan mtg corp":"fhlmc",
    "f home loan mtg corp":"fhlmc",
    "federal hm loan mtg corp":"fhlmc",
    "fedl hm loan mtg corp":"fhlmc",
    "fed hm loan mtg corp":"fhlmc",
    "f hm loan mtg corp":"fhlmc",
    "federal h loan mtg corp":"fhlmc",
    "fedl h loan mtg corp":"fhlmc",
    "fed h loan mtg corp":"fhlmc",
    "f h loan mtg corp":"fhlmc",
    "federal home ln mtg corp":"fhlmc",
    "fedl home ln mtg corp":"fhlmc",
    "fed home ln mtg corp":"fhlmc",
    "f home ln mtg corp":"fhlmc",
    "federal hm ln mtg corp":"fhlmc",
    "fedl hm ln mtg corp":"fhlmc",
    "fed hm ln mtg corp":"fhlmc",
    "f hm ln mtg corp":"fhlmc",
    "federal h ln mtg corp":"fhlmc",
    "fedl h ln mtg corp":"fhlmc",
    "fed h ln mtg corp":"fhlmc",
    "f h ln mtg corp":"fhlmc",
    "federal home l mtg corp":"fhlmc",
    "fedl home l mtg corp":"fhlmc",
    "fed home l mtg corp":"fhlmc",
    "f home l mtg corp":"fhlmc",
    "federal hm l mtg corp":"fhlmc",
    "fedl hm l mtg corp":"fhlmc",
    "fed hm l mtg corp":"fhlmc",
    "f hm l mtg corp":"fhlmc",
    "federal h l mtg corp":"fhlmc",
    "fedl h l mtg corp":"fhlmc",
    "fed h l mtg corp":"fhlmc",
    "f h l mtg corp":"fhlmc",
    "federal home loan m corp":"fhlmc",
    "fedl home loan m corp":"fhlmc",
    "fed home loan m corp":"fhlmc",
    "f home loan m corp":"fhlmc",
    "federal hm loan m corp":"fhlmc",
    "fedl hm loan m corp":"fhlmc",
    "fed hm loan m corp":"fhlmc",
    "f hm loan m corp":"fhlmc",
    "federal h loan m corp":"fhlmc",
    "fedl h loan m corp":"fhlmc",
    "fed h loan m corp":"fhlmc",
    "f h loan m corp":"fhlmc",
    "federal home ln m corp":"fhlmc",
    "fedl home ln m corp":"fhlmc",
    "fed home ln m corp":"fhlmc",
    "f home ln m corp":"fhlmc",
    "federal hm ln m corp":"fhlmc",
    "fedl hm ln m corp":"fhlmc",
    "fed hm ln m corp":"fhlmc",
    "f hm ln m corp":"fhlmc",
    "federal h ln m corp":"fhlmc",
    "fedl h ln m corp":"fhlmc",
    "fed h ln m corp":"fhlmc",
    "f h ln m corp":"fhlmc",
    "federal home l m corp":"fhlmc",
    "fedl home l m corp":"fhlmc",
    "fed home l m corp":"fhlmc",
    "f home l m corp":"fhlmc",
    "federal hm l m corp":"fhlmc",
    "fedl hm l m corp":"fhlmc",
    "fed hm l m corp":"fhlmc",
    "f hm l m corp":"fhlmc",
    "federal h l m corp":"fhlmc",
    "fedl h l m corp":"fhlmc",
    "fed h l m corp":"fhlmc",
    "f h l m corp":"fhlmc",
    "federal home loan mortgage c":"fhlmc",
    "fedl home loan mortgage c":"fhlmc",
    "fed home loan mortgage c":"fhlmc",
    "f home loan mortgage c":"fhlmc",
    "federal hm loan mortgage c":"fhlmc",
    "fedl hm loan mortgage c":"fhlmc",
    "fed hm loan mortgage c":"fhlmc",
    "f hm loan mortgage c":"fhlmc",
    "federal h loan mortgage c":"fhlmc",
    "fedl h loan mortgage c":"fhlmc",
    "fed h loan mortgage c":"fhlmc",
    "f h loan mortgage c":"fhlmc",
    "federal home ln mortgage c":"fhlmc",
    "fedl home ln mortgage c":"fhlmc",
    "fed home ln mortgage c":"fhlmc",
    "f home ln mortgage c":"fhlmc",
    "federal hm ln mortgage c":"fhlmc",
    "fedl hm ln mortgage c":"fhlmc",
    "fed hm ln mortgage c":"fhlmc",
    "f hm ln mortgage c":"fhlmc",
    "federal h ln mortgage c":"fhlmc",
    "fedl h ln mortgage c":"fhlmc",
    "fed h ln mortgage c":"fhlmc",
    "f h ln mortgage c":"fhlmc",
    "federal home l mortgage c":"fhlmc",
    "fedl home l mortgage c":"fhlmc",
    "fed home l mortgage c":"fhlmc",
    "f home l mortgage c":"fhlmc",
    "federal hm l mortgage c":"fhlmc",
    "fedl hm l mortgage c":"fhlmc",
    "fed hm l mortgage c":"fhlmc",
    "f hm l mortgage c":"fhlmc",
    "federal h l mortgage c":"fhlmc",
    "fedl h l mortgage c":"fhlmc",
    "fed h l mortgage c":"fhlmc",
    "f h l mortgage c":"fhlmc",
    "federal home loan mtge c":"fhlmc",
    "fedl home loan mtge c":"fhlmc",
    "fed home loan mtge c":"fhlmc",
    "f home loan mtge c":"fhlmc",
    "federal hm loan mtge c":"fhlmc",
    "fedl hm loan mtge c":"fhlmc",
    "fed hm loan mtge c":"fhlmc",
    "f hm loan mtge c":"fhlmc",
    "federal h loan mtge c":"fhlmc",
    "fedl h loan mtge c":"fhlmc",
    "fed h loan mtge c":"fhlmc",
    "f h loan mtge c":"fhlmc",
    "federal home ln mtge c":"fhlmc",
    "fedl home ln mtge c":"fhlmc",
    "fed home ln mtge c":"fhlmc",
    "f home ln mtge c":"fhlmc",
    "federal hm ln mtge c":"fhlmc",
    "fedl hm ln mtge c":"fhlmc",
    "fed hm ln mtge c":"fhlmc",
    "f hm ln mtge c":"fhlmc",
    "federal h ln mtge c":"fhlmc",
    "fedl h ln mtge c":"fhlmc",
    "fed h ln mtge c":"fhlmc",
    "f h ln mtge c":"fhlmc",
    "federal home l mtge c":"fhlmc",
    "fedl home l mtge c":"fhlmc",
    "fed home l mtge c":"fhlmc",
    "f home l mtge c":"fhlmc",
    "federal hm l mtge c":"fhlmc",
    "fedl hm l mtge c":"fhlmc",
    "fed hm l mtge c":"fhlmc",
    "f hm l mtge c":"fhlmc",
    "federal h l mtge c":"fhlmc",
    "fedl h l mtge c":"fhlmc",
    "fed h l mtge c":"fhlmc",
    "f h l mtge c":"fhlmc",
    "federal home loan mtg c":"fhlmc",
    "fedl home loan mtg c":"fhlmc",
    "fed home loan mtg c":"fhlmc",
    "f home loan mtg c":"fhlmc",
    "federal hm loan mtg c":"fhlmc",
    "fedl hm loan mtg c":"fhlmc",
    "fed hm loan mtg c":"fhlmc",
    "f hm loan mtg c":"fhlmc",
    "federal h loan mtg c":"fhlmc",
    "fedl h loan mtg c":"fhlmc",
    "fed h loan mtg c":"fhlmc",
    "f h loan mtg c":"fhlmc",
    "federal home ln mtg c":"fhlmc",
    "fedl home ln mtg c":"fhlmc",
    "fed home ln mtg c":"fhlmc",
    "f home ln mtg c":"fhlmc",
    "federal hm ln mtg c":"fhlmc",
    "fedl hm ln mtg c":"fhlmc",
    "fed hm ln mtg c":"fhlmc",
    "f hm ln mtg c":"fhlmc",
    "federal h ln mtg c":"fhlmc",
    "fedl h ln mtg c":"fhlmc",
    "fed h ln mtg c":"fhlmc",
    "f h ln mtg c":"fhlmc",
    "federal home l mtg c":"fhlmc",
    "fedl home l mtg c":"fhlmc",
    "fed home l mtg c":"fhlmc",
    "f home l mtg c":"fhlmc",
    "federal hm l mtg c":"fhlmc",
    "fedl hm l mtg c":"fhlmc",
    "fed hm l mtg c":"fhlmc",
    "f hm l mtg c":"fhlmc",
    "federal h l mtg c":"fhlmc",
    "fedl h l mtg c":"fhlmc",
    "fed h l mtg c":"fhlmc",
    "f h l mtg c":"fhlmc",
    "federal home loan m c":"fhlmc",
    "fedl home loan m c":"fhlmc",
    "fed home loan m c":"fhlmc",
    "f home loan m c":"fhlmc",
    "federal hm loan m c":"fhlmc",
    "fedl hm loan m c":"fhlmc",
    "fed hm loan m c":"fhlmc",
    "f hm loan m c":"fhlmc",
    "federal h loan m c":"fhlmc",
    "fedl h loan m c":"fhlmc",
    "fed h loan m c":"fhlmc",
    "f h loan m c":"fhlmc",
    "federal home ln m c":"fhlmc",
    "fedl home ln m c":"fhlmc",
    "fed home ln m c":"fhlmc",
    "f home ln m c":"fhlmc",
    "federal hm ln m c":"fhlmc",
    "fedl hm ln m c":"fhlmc",
    "fed hm ln m c":"fhlmc",
    "f hm ln m c":"fhlmc",
    "federal h ln m c":"fhlmc",
    "fedl h ln m c":"fhlmc",
    "fed h ln m c":"fhlmc",
    "f h ln m c":"fhlmc",
    "federal home l m c":"fhlmc",
    "fedl home l m c":"fhlmc",
    "fed home l m c":"fhlmc",
    "f home l m c":"fhlmc",
    "federal hm l m c":"fhlmc",
    "fedl hm l m c":"fhlmc",
    "fed hm l m c":"fhlmc",
    "f hm l m c":"fhlmc",
    "federal h l m c":"fhlmc",
    "fedl h l m c":"fhlmc",
    "fed h l m c":"fhlmc",
    "f h l m c":"fhlmc",
    "freddie mac":"fhlmc",

    # FDIC
    "federal deposit insurance corporation":"fdic",
    "fed deposit insurance corporation":"fdic",
    "f deposit insurance corporation":"fdic",
    "federal dep insurance corporation":"fdic",
    "fed dep insurance corporation":"fdic",
    "f dep insurance corporation":"fdic",
    "federal d insurance corporation":"fdic",
    "fed d insurance corporation":"fdic",
    "f d insurance corporation":"fdic",
    "federal deposit ins corporation":"fdic",
    "fed deposit ins corporation":"fdic",
    "f deposit ins corporation":"fdic",
    "federal dep ins corporation":"fdic",
    "fed dep ins corporation":"fdic",
    "f dep ins corporation":"fdic",
    "federal d ins corporation":"fdic",
    "fed d ins corporation":"fdic",
    "f d ins corporation":"fdic",
    "federal deposit i corporation":"fdic",
    "fed deposit i corporation":"fdic",
    "f deposit i corporation":"fdic",
    "federal dep i corporation":"fdic",
    "fed dep i corporation":"fdic",
    "f dep i corporation":"fdic",
    "federal d i corporation":"fdic",
    "fed d i corporation":"fdic",
    "f d i corporation":"fdic",
    "federal deposit insurance corp":"fdic",
    "fed deposit insurance corp":"fdic",
    "f deposit insurance corp":"fdic",
    "federal dep insurance corp":"fdic",
    "fed dep insurance corp":"fdic",
    "f dep insurance corp":"fdic",
    "federal d insurance corp":"fdic",
    "fed d insurance corp":"fdic",
    "f d insurance corp":"fdic",
    "federal deposit ins corp":"fdic",
    "fed deposit ins corp":"fdic",
    "f deposit ins corp":"fdic",
    "federal dep ins corp":"fdic",
    "fed dep ins corp":"fdic",
    "f dep ins corp":"fdic",
    "federal d ins corp":"fdic",
    "fed d ins corp":"fdic",
    "f d ins corp":"fdic",
    "federal deposit i corp":"fdic",
    "fed deposit i corp":"fdic",
    "f deposit i corp":"fdic",
    "federal dep i corp":"fdic",
    "fed dep i corp":"fdic",
    "f dep i corp":"fdic",
    "federal d i corp":"fdic",
    "fed d i corp":"fdic",
    "f d i corp":"fdic",
    "federal deposit insurance c":"fdic",
    "fed deposit insurance c":"fdic",
    "f deposit insurance c":"fdic",
    "federal dep insurance c":"fdic",
    "fed dep insurance c":"fdic",
    "f dep insurance c":"fdic",
    "federal d insurance c":"fdic",
    "fed d insurance c":"fdic",
    "f d insurance c":"fdic",
    "federal deposit ins c":"fdic",
    "fed deposit ins c":"fdic",
    "f deposit ins c":"fdic",
    "federal dep ins c":"fdic",
    "fed dep ins c":"fdic",
    "f dep ins c":"fdic",
    "federal d ins c":"fdic",
    "fed d ins c":"fdic",
    "f d ins c":"fdic",
    "federal deposit i c":"fdic",
    "fed deposit i c":"fdic",
    "f deposit i c":"fdic",
    "federal dep i c":"fdic",
    "fed dep i c":"fdic",
    "f dep i c":"fdic",
    "federal d i c":"fdic",
    "fed d i c":"fdic",
    "f d i c":"fdic",

    # GNMA
    "government national mortgage association":"gnma",
    "govt national mortgage association":"gnma",
    "gov national mortgage association":"gnma",
    "g national mortgage association":"gnma",
    "government natl mortgage association":"gnma",
    "govt natl mortgage association":"gnma",
    "gov natl mortgage association":"gnma",
    "g natl mortgage association":"gnma",
    "government nat mortgage association":"gnma",
    "govt nat mortgage association":"gnma",
    "gov nat mortgage association":"gnma",
    "g nat mortgage association":"gnma",
    "government n mortgage association":"gnma",
    "govt n mortgage association":"gnma",
    "gov n mortgage association":"gnma",
    "g n mortgage association":"gnma",
    "government national mtge association":"gnma",
    "govt national mtge association":"gnma",
    "gov national mtge association":"gnma",
    "g national mtge association":"gnma",
    "government natl mtge association":"gnma",
    "govt natl mtge association":"gnma",
    "gov natl mtge association":"gnma",
    "g natl mtge association":"gnma",
    "government nat mtge association":"gnma",
    "govt nat mtge association":"gnma",
    "gov nat mtge association":"gnma",
    "g nat mtge association":"gnma",
    "government n mtge association":"gnma",
    "govt n mtge association":"gnma",
    "gov n mtge association":"gnma",
    "g n mtge association":"gnma",
    "government national mtg association":"gnma",
    "govt national mtg association":"gnma",
    "gov national mtg association":"gnma",
    "g national mtg association":"gnma",
    "government natl mtg association":"gnma",
    "govt natl mtg association":"gnma",
    "gov natl mtg association":"gnma",
    "g natl mtg association":"gnma",
    "government nat mtg association":"gnma",
    "govt nat mtg association":"gnma",
    "gov nat mtg association":"gnma",
    "g nat mtg association":"gnma",
    "government n mtg association":"gnma",
    "govt n mtg association":"gnma",
    "gov n mtg association":"gnma",
    "g n mtg association":"gnma",
    "government national m association":"gnma",
    "govt national m association":"gnma",
    "gov national m association":"gnma",
    "g national m association":"gnma",
    "government natl m association":"gnma",
    "govt natl m association":"gnma",
    "gov natl m association":"gnma",
    "g natl m association":"gnma",
    "government nat m association":"gnma",
    "govt nat m association":"gnma",
    "gov nat m association":"gnma",
    "g nat m association":"gnma",
    "government n m association":"gnma",
    "govt n m association":"gnma",
    "gov n m association":"gnma",
    "g n m association":"gnma",
    "government national mortgage assoc":"gnma",
    "govt national mortgage assoc":"gnma",
    "gov national mortgage assoc":"gnma",
    "g national mortgage assoc":"gnma",
    "government natl mortgage assoc":"gnma",
    "govt natl mortgage assoc":"gnma",
    "gov natl mortgage assoc":"gnma",
    "g natl mortgage assoc":"gnma",
    "government nat mortgage assoc":"gnma",
    "govt nat mortgage assoc":"gnma",
    "gov nat mortgage assoc":"gnma",
    "g nat mortgage assoc":"gnma",
    "government n mortgage assoc":"gnma",
    "govt n mortgage assoc":"gnma",
    "gov n mortgage assoc":"gnma",
    "g n mortgage assoc":"gnma",
    "government national mtge assoc":"gnma",
    "govt national mtge assoc":"gnma",
    "gov national mtge assoc":"gnma",
    "g national mtge assoc":"gnma",
    "government natl mtge assoc":"gnma",
    "govt natl mtge assoc":"gnma",
    "gov natl mtge assoc":"gnma",
    "g natl mtge assoc":"gnma",
    "government nat mtge assoc":"gnma",
    "govt nat mtge assoc":"gnma",
    "gov nat mtge assoc":"gnma",
    "g nat mtge assoc":"gnma",
    "government n mtge assoc":"gnma",
    "govt n mtge assoc":"gnma",
    "gov n mtge assoc":"gnma",
    "g n mtge assoc":"gnma",
    "government national mtg assoc":"gnma",
    "govt national mtg assoc":"gnma",
    "gov national mtg assoc":"gnma",
    "g national mtg assoc":"gnma",
    "government natl mtg assoc":"gnma",
    "govt natl mtg assoc":"gnma",
    "gov natl mtg assoc":"gnma",
    "g natl mtg assoc":"gnma",
    "government nat mtg assoc":"gnma",
    "govt nat mtg assoc":"gnma",
    "gov nat mtg assoc":"gnma",
    "g nat mtg assoc":"gnma",
    "government n mtg assoc":"gnma",
    "govt n mtg assoc":"gnma",
    "gov n mtg assoc":"gnma",
    "g n mtg assoc":"gnma",
    "government national m assoc":"gnma",
    "govt national m assoc":"gnma",
    "gov national m assoc":"gnma",
    "g national m assoc":"gnma",
    "government natl m assoc":"gnma",
    "govt natl m assoc":"gnma",
    "gov natl m assoc":"gnma",
    "g natl m assoc":"gnma",
    "government nat m assoc":"gnma",
    "govt nat m assoc":"gnma",
    "gov nat m assoc":"gnma",
    "g nat m assoc":"gnma",
    "government n m assoc":"gnma",
    "govt n m assoc":"gnma",
    "gov n m assoc":"gnma",
    "g n m assoc":"gnma",
    "government national mortgage assn":"gnma",
    "govt national mortgage assn":"gnma",
    "gov national mortgage assn":"gnma",
    "g national mortgage assn":"gnma",
    "government natl mortgage assn":"gnma",
    "govt natl mortgage assn":"gnma",
    "gov natl mortgage assn":"gnma",
    "g natl mortgage assn":"gnma",
    "government nat mortgage assn":"gnma",
    "govt nat mortgage assn":"gnma",
    "gov nat mortgage assn":"gnma",
    "g nat mortgage assn":"gnma",
    "government n mortgage assn":"gnma",
    "govt n mortgage assn":"gnma",
    "gov n mortgage assn":"gnma",
    "g n mortgage assn":"gnma",
    "government national mtge assn":"gnma",
    "govt national mtge assn":"gnma",
    "gov national mtge assn":"gnma",
    "g national mtge assn":"gnma",
    "government natl mtge assn":"gnma",
    "govt natl mtge assn":"gnma",
    "gov natl mtge assn":"gnma",
    "g natl mtge assn":"gnma",
    "government nat mtge assn":"gnma",
    "govt nat mtge assn":"gnma",
    "gov nat mtge assn":"gnma",
    "g nat mtge assn":"gnma",
    "government n mtge assn":"gnma",
    "govt n mtge assn":"gnma",
    "gov n mtge assn":"gnma",
    "g n mtge assn":"gnma",
    "government national mtg assn":"gnma",
    "govt national mtg assn":"gnma",
    "gov national mtg assn":"gnma",
    "g national mtg assn":"gnma",
    "government natl mtg assn":"gnma",
    "govt natl mtg assn":"gnma",
    "gov natl mtg assn":"gnma",
    "g natl mtg assn":"gnma",
    "government nat mtg assn":"gnma",
    "govt nat mtg assn":"gnma",
    "gov nat mtg assn":"gnma",
    "g nat mtg assn":"gnma",
    "government n mtg assn":"gnma",
    "govt n mtg assn":"gnma",
    "gov n mtg assn":"gnma",
    "g n mtg assn":"gnma",
    "government national m assn":"gnma",
    "govt national m assn":"gnma",
    "gov national m assn":"gnma",
    "g national m assn":"gnma",
    "government natl m assn":"gnma",
    "govt natl m assn":"gnma",
    "gov natl m assn":"gnma",
    "g natl m assn":"gnma",
    "government nat m assn":"gnma",
    "govt nat m assn":"gnma",
    "gov nat m assn":"gnma",
    "g nat m assn":"gnma",
    "government n m assn":"gnma",
    "govt n m assn":"gnma",
    "gov n m assn":"gnma",
    "g n m assn":"gnma",
    "government national mortgage a":"gnma",
    "govt national mortgage a":"gnma",
    "gov national mortgage a":"gnma",
    "g national mortgage a":"gnma",
    "government natl mortgage a":"gnma",
    "govt natl mortgage a":"gnma",
    "gov natl mortgage a":"gnma",
    "g natl mortgage a":"gnma",
    "government nat mortgage a":"gnma",
    "govt nat mortgage a":"gnma",
    "gov nat mortgage a":"gnma",
    "g nat mortgage a":"gnma",
    "government n mortgage a":"gnma",
    "govt n mortgage a":"gnma",
    "gov n mortgage a":"gnma",
    "g n mortgage a":"gnma",
    "government national mtge a":"gnma",
    "govt national mtge a":"gnma",
    "gov national mtge a":"gnma",
    "g national mtge a":"gnma",
    "government natl mtge a":"gnma",
    "govt natl mtge a":"gnma",
    "gov natl mtge a":"gnma",
    "g natl mtge a":"gnma",
    "government nat mtge a":"gnma",
    "govt nat mtge a":"gnma",
    "gov nat mtge a":"gnma",
    "g nat mtge a":"gnma",
    "government n mtge a":"gnma",
    "govt n mtge a":"gnma",
    "gov n mtge a":"gnma",
    "g n mtge a":"gnma",
    "government national mtg a":"gnma",
    "govt national mtg a":"gnma",
    "gov national mtg a":"gnma",
    "g national mtg a":"gnma",
    "government natl mtg a":"gnma",
    "govt natl mtg a":"gnma",
    "gov natl mtg a":"gnma",
    "g natl mtg a":"gnma",
    "government nat mtg a":"gnma",
    "govt nat mtg a":"gnma",
    "gov nat mtg a":"gnma",
    "g nat mtg a":"gnma",
    "government n mtg a":"gnma",
    "govt n mtg a":"gnma",
    "gov n mtg a":"gnma",
    "g n mtg a":"gnma",
    "government national m a":"gnma",
    "govt national m a":"gnma",
    "gov national m a":"gnma",
    "g national m a":"gnma",
    "government natl m a":"gnma",
    "govt natl m a":"gnma",
    "gov natl m a":"gnma",
    "g natl m a":"gnma",
    "government nat m a":"gnma",
    "govt nat m a":"gnma",
    "gov nat m a":"gnma",
    "g nat m a":"gnma",
    "government n m a":"gnma",
    "govt n m a":"gnma",
    "gov n m a":"gnma",
    "g n m a":"gnma",
    "ginnie mae":"gnma",

    # FAMC
    "federal agricultural mortgage corporation":"famc",
    "fedl agricultural mortgage corporation":"famc",
    "fed agricultural mortgage corporation":"famc",
    "f agricultural mortgage corporation":"famc",
    "federal ag mortgage corporation":"famc",
    "fedl ag mortgage corporation":"famc",
    "fed ag mortgage corporation":"famc",
    "f ag mortgage corporation":"famc",
    "federal a mortgage corporation":"famc",
    "fedl a mortgage corporation":"famc",
    "fed a mortgage corporation":"famc",
    "f a mortgage corporation":"famc",
    "federal agricultural mtge corporation":"famc",
    "fedl agricultural mtge corporation":"famc",
    "fed agricultural mtge corporation":"famc",
    "f agricultural mtge corporation":"famc",
    "federal ag mtge corporation":"famc",
    "fedl ag mtge corporation":"famc",
    "fed ag mtge corporation":"famc",
    "f ag mtge corporation":"famc",
    "federal a mtge corporation":"famc",
    "fedl a mtge corporation":"famc",
    "fed a mtge corporation":"famc",
    "f a mtge corporation":"famc",
    "federal agricultural mtg corporation":"famc",
    "fedl agricultural mtg corporation":"famc",
    "fed agricultural mtg corporation":"famc",
    "f agricultural mtg corporation":"famc",
    "federal ag mtg corporation":"famc",
    "fedl ag mtg corporation":"famc",
    "fed ag mtg corporation":"famc",
    "f ag mtg corporation":"famc",
    "federal a mtg corporation":"famc",
    "fedl a mtg corporation":"famc",
    "fed a mtg corporation":"famc",
    "f a mtg corporation":"famc",
    "federal agricultural m corporation":"famc",
    "fedl agricultural m corporation":"famc",
    "fed agricultural m corporation":"famc",
    "f agricultural m corporation":"famc",
    "federal ag m corporation":"famc",
    "fedl ag m corporation":"famc",
    "fed ag m corporation":"famc",
    "f ag m corporation":"famc",
    "federal a m corporation":"famc",
    "fedl a m corporation":"famc",
    "fed a m corporation":"famc",
    "f a m corporation":"famc",
    "federal agricultural mortgage corp":"famc",
    "fedl agricultural mortgage corp":"famc",
    "fed agricultural mortgage corp":"famc",
    "f agricultural mortgage corp":"famc",
    "federal ag mortgage corp":"famc",
    "fedl ag mortgage corp":"famc",
    "fed ag mortgage corp":"famc",
    "f ag mortgage corp":"famc",
    "federal a mortgage corp":"famc",
    "fedl a mortgage corp":"famc",
    "fed a mortgage corp":"famc",
    "f a mortgage corp":"famc",
    "federal agricultural mtge corp":"famc",
    "fedl agricultural mtge corp":"famc",
    "fed agricultural mtge corp":"famc",
    "f agricultural mtge corp":"famc",
    "federal ag mtge corp":"famc",
    "fedl ag mtge corp":"famc",
    "fed ag mtge corp":"famc",
    "f ag mtge corp":"famc",
    "federal a mtge corp":"famc",
    "fedl a mtge corp":"famc",
    "fed a mtge corp":"famc",
    "f a mtge corp":"famc",
    "federal agricultural mtg corp":"famc",
    "fedl agricultural mtg corp":"famc",
    "fed agricultural mtg corp":"famc",
    "f agricultural mtg corp":"famc",
    "federal ag mtg corp":"famc",
    "fedl ag mtg corp":"famc",
    "fed ag mtg corp":"famc",
    "f ag mtg corp":"famc",
    "federal a mtg corp":"famc",
    "fedl a mtg corp":"famc",
    "fed a mtg corp":"famc",
    "f a mtg corp":"famc",
    "federal agricultural m corp":"famc",
    "fedl agricultural m corp":"famc",
    "fed agricultural m corp":"famc",
    "f agricultural m corp":"famc",
    "federal ag m corp":"famc",
    "fedl ag m corp":"famc",
    "fed ag m corp":"famc",
    "f ag m corp":"famc",
    "federal a m corp":"famc",
    "fedl a m corp":"famc",
    "fed a m corp":"famc",
    "f a m corp":"famc",
    "federal agricultural mortgage c":"famc",
    "fedl agricultural mortgage c":"famc",
    "fed agricultural mortgage c":"famc",
    "f agricultural mortgage c":"famc",
    "federal ag mortgage c":"famc",
    "fedl ag mortgage c":"famc",
    "fed ag mortgage c":"famc",
    "f ag mortgage c":"famc",
    "federal a mortgage c":"famc",
    "fedl a mortgage c":"famc",
    "fed a mortgage c":"famc",
    "f a mortgage c":"famc",
    "federal agricultural mtge c":"famc",
    "fedl agricultural mtge c":"famc",
    "fed agricultural mtge c":"famc",
    "f agricultural mtge c":"famc",
    "federal ag mtge c":"famc",
    "fedl ag mtge c":"famc",
    "fed ag mtge c":"famc",
    "f ag mtge c":"famc",
    "federal a mtge c":"famc",
    "fedl a mtge c":"famc",
    "fed a mtge c":"famc",
    "f a mtge c":"famc",
    "federal agricultural mtg c":"famc",
    "fedl agricultural mtg c":"famc",
    "fed agricultural mtg c":"famc",
    "f agricultural mtg c":"famc",
    "federal ag mtg c":"famc",
    "fedl ag mtg c":"famc",
    "fed ag mtg c":"famc",
    "f ag mtg c":"famc",
    "federal a mtg c":"famc",
    "fedl a mtg c":"famc",
    "fed a mtg c":"famc",
    "f a mtg c":"famc",
    "federal agricultural m c":"famc",
    "fedl agricultural m c":"famc",
    "fed agricultural m c":"famc",
    "f agricultural m c":"famc",
    "federal ag m c":"famc",
    "fedl ag m c":"famc",
    "fed ag m c":"famc",
    "f ag m c":"famc",
    "federal a m c":"famc",
    "fedl a m c":"famc",
    "fed a m c":"famc",
    "f a m c":"famc",
    "farmer mac":"famc",

    # HUD
    "department of housing and urban development":"hud",
    "dept of housing and urban development":"hud",
    "dep of housing and urban development":"hud",
    "department housing and urban development":"hud",
    "dept housing and urban development":"hud",
    "dep housing and urban development":"hud",
    "housing and urban development":"hud",
    "department of h and urban development":"hud",
    "dept of h and urban development":"hud",
    "dep of h and urban development":"hud",
    "department h and urban development":"hud",
    "dept h and urban development":"hud",
    "dep h and urban development":"hud",
    "h and urban development":"hud",
    "department of housing & urban development":"hud",
    "dept of housing & urban development":"hud",
    "dep of housing & urban development":"hud",
    "department housing & urban development":"hud",
    "dept housing & urban development":"hud",
    "dep housing & urban development":"hud",
    "housing & urban development":"hud",
    "department of h & urban development":"hud",
    "dept of h & urban development":"hud",
    "dep of h & urban development":"hud",
    "department h & urban development":"hud",
    "dept h & urban development":"hud",
    "dep h & urban development":"hud",
    "h & urban development":"hud",
    "department of housing and urb development":"hud",
    "dept of housing and urb development":"hud",
    "dep of housing and urb development":"hud",
    "department housing and urb development":"hud",
    "dept housing and urb development":"hud",
    "dep housing and urb development":"hud",
    "housing and urb development":"hud",
    "department of h and urb development":"hud",
    "dept of h and urb development":"hud",
    "dep of h and urb development":"hud",
    "department h and urb development":"hud",
    "dept h and urb development":"hud",
    "dep h and urb development":"hud",
    "h and urb development":"hud",
    "department of housing & urb development":"hud",
    "dept of housing & urb development":"hud",
    "dep of housing & urb development":"hud",
    "department housing & urb development":"hud",
    "dept housing & urb development":"hud",
    "dep housing & urb development":"hud",
    "housing & urb development":"hud",
    "department of h & urb development":"hud",
    "dept of h & urb development":"hud",
    "dep of h & urb development":"hud",
    "department h & urb development":"hud",
    "dept h & urb development":"hud",
    "dep h & urb development":"hud",
    "h & urb development":"hud",
    "department of housing and u development":"hud",
    "dept of housing and u development":"hud",
    "dep of housing and u development":"hud",
    "department housing and u development":"hud",
    "dept housing and u development":"hud",
    "dep housing and u development":"hud",
    "housing and u development":"hud",
    "department of h and u development":"hud",
    "dept of h and u development":"hud",
    "dep of h and u development":"hud",
    "department h and u development":"hud",
    "dept h and u development":"hud",
    "dep h and u development":"hud",
    "h and u development":"hud",
    "department of housing & u development":"hud",
    "dept of housing & u development":"hud",
    "dep of housing & u development":"hud",
    "department housing & u development":"hud",
    "dept housing & u development":"hud",
    "dep housing & u development":"hud",
    "housing & u development":"hud",
    "department of h & u development":"hud",
    "dept of h & u development":"hud",
    "dep of h & u development":"hud",
    "department h & u development":"hud",
    "dept h & u development":"hud",
    "dep h & u development":"hud",
    "h & u development":"hud",
    "department of housing and urban dev":"hud",
    "dept of housing and urban dev":"hud",
    "dep of housing and urban dev":"hud",
    "department housing and urban dev":"hud",
    "dept housing and urban dev":"hud",
    "dep housing and urban dev":"hud",
    "housing and urban dev":"hud",
    "department of h and urban dev":"hud",
    "dept of h and urban dev":"hud",
    "dep of h and urban dev":"hud",
    "department h and urban dev":"hud",
    "dept h and urban dev":"hud",
    "dep h and urban dev":"hud",
    "h and urban dev":"hud",
    "department of housing & urban dev":"hud",
    "dept of housing & urban dev":"hud",
    "dep of housing & urban dev":"hud",
    "department housing & urban dev":"hud",
    "dept housing & urban dev":"hud",
    "dep housing & urban dev":"hud",
    "housing & urban dev":"hud",
    "department of h & urban dev":"hud",
    "dept of h & urban dev":"hud",
    "dep of h & urban dev":"hud",
    "department h & urban dev":"hud",
    "dept h & urban dev":"hud",
    "dep h & urban dev":"hud",
    "h & urban dev":"hud",
    "department of housing and urb dev":"hud",
    "dept of housing and urb dev":"hud",
    "dep of housing and urb dev":"hud",
    "department housing and urb dev":"hud",
    "dept housing and urb dev":"hud",
    "dep housing and urb dev":"hud",
    "housing and urb dev":"hud",
    "department of h and urb dev":"hud",
    "dept of h and urb dev":"hud",
    "dep of h and urb dev":"hud",
    "department h and urb dev":"hud",
    "dept h and urb dev":"hud",
    "dep h and urb dev":"hud",
    "h and urb dev":"hud",
    "department of housing & urb dev":"hud",
    "dept of housing & urb dev":"hud",
    "dep of housing & urb dev":"hud",
    "department housing & urb dev":"hud",
    "dept housing & urb dev":"hud",
    "dep housing & urb dev":"hud",
    "housing & urb dev":"hud",
    "department of h & urb dev":"hud",
    "dept of h & urb dev":"hud",
    "dep of h & urb dev":"hud",
    "department h & urb dev":"hud",
    "dept h & urb dev":"hud",
    "dep h & urb dev":"hud",
    "h & urb dev":"hud",
    "department of housing and u dev":"hud",
    "dept of housing and u dev":"hud",
    "dep of housing and u dev":"hud",
    "department housing and u dev":"hud",
    "dept housing and u dev":"hud",
    "dep housing and u dev":"hud",
    "housing and u dev":"hud",
    "department of h and u dev":"hud",
    "dept of h and u dev":"hud",
    "dep of h and u dev":"hud",
    "department h and u dev":"hud",
    "dept h and u dev":"hud",
    "dep h and u dev":"hud",
    "h and u dev":"hud",
    "department of housing & u dev":"hud",
    "dept of housing & u dev":"hud",
    "dep of housing & u dev":"hud",
    "department housing & u dev":"hud",
    "dept housing & u dev":"hud",
    "dep housing & u dev":"hud",
    "housing & u dev":"hud",
    "department of h & u dev":"hud",
    "dept of h & u dev":"hud",
    "dep of h & u dev":"hud",
    "department h & u dev":"hud",
    "dept h & u dev":"hud",
    "dep h & u dev":"hud",
    "h & u dev":"hud",
    "department of housing and urban d":"hud",
    "dept of housing and urban d":"hud",
    "dep of housing and urban d":"hud",
    "department housing and urban d":"hud",
    "dept housing and urban d":"hud",
    "dep housing and urban d":"hud",
    "housing and urban d":"hud",
    "department of h and urban d":"hud",
    "dept of h and urban d":"hud",
    "dep of h and urban d":"hud",
    "department h and urban d":"hud",
    "dept h and urban d":"hud",
    "dep h and urban d":"hud",
    "h and urban d":"hud",
    "department of housing & urban d":"hud",
    "dept of housing & urban d":"hud",
    "dep of housing & urban d":"hud",
    "department housing & urban d":"hud",
    "dept housing & urban d":"hud",
    "dep housing & urban d":"hud",
    "housing & urban d":"hud",
    "department of h & urban d":"hud",
    "dept of h & urban d":"hud",
    "dep of h & urban d":"hud",
    "department h & urban d":"hud",
    "dept h & urban d":"hud",
    "dep h & urban d":"hud",
    "h & urban d":"hud",
    "department of housing and urb d":"hud",
    "dept of housing and urb d":"hud",
    "dep of housing and urb d":"hud",
    "department housing and urb d":"hud",
    "dept housing and urb d":"hud",
    "dep housing and urb d":"hud",
    "housing and urb d":"hud",
    "department of h and urb d":"hud",
    "dept of h and urb d":"hud",
    "dep of h and urb d":"hud",
    "department h and urb d":"hud",
    "dept h and urb d":"hud",
    "dep h and urb d":"hud",
    "h and urb d":"hud",
    "department of housing & urb d":"hud",
    "dept of housing & urb d":"hud",
    "dep of housing & urb d":"hud",
    "department housing & urb d":"hud",
    "dept housing & urb d":"hud",
    "dep housing & urb d":"hud",
    "housing & urb d":"hud",
    "department of h & urb d":"hud",
    "dept of h & urb d":"hud",
    "dep of h & urb d":"hud",
    "department h & urb d":"hud",
    "dept h & urb d":"hud",
    "dep h & urb d":"hud",
    "h & urb d":"hud",
    "department of housing and u d":"hud",
    "dept of housing and u d":"hud",
    "dep of housing and u d":"hud",
    "department housing and u d":"hud",
    "dept housing and u d":"hud",
    "dep housing and u d":"hud",
    "housing and u d":"hud",
    "department of h and u d":"hud",
    "dept of h and u d":"hud",
    "dep of h and u d":"hud",
    "department h and u d":"hud",
    "dept h and u d":"hud",
    "dep h and u d":"hud",
    "h and u d":"hud",
    "department of housing & u d":"hud",
    "dept of housing & u d":"hud",
    "dep of housing & u d":"hud",
    "department housing & u d":"hud",
    "dept housing & u d":"hud",
    "dep housing & u d":"hud",
    "housing & u d":"hud",
    "department of h & u d":"hud",
    "dept of h & u d":"hud",
    "dep of h & u d":"hud",
    "department h & u d":"hud",
    "dept h & u d":"hud",
    "dep h & u d":"hud",
    "h & u d":"hud",
    "h u d":"hud",

    # FHA
    "federal housing administration":"fha",
    "fedl housing administration":"fha",
    "fed housing administration":"fha",
    "f housing administration":"fha",
    "federal h administration":"fha",
    "fedl h administration":"fha",
    "fed h administration":"fha",
    "f h administration":"fha",
    "federal housing admin":"fha",
    "fedl housing admin":"fha",
    "fed housing admin":"fha",
    "f housing admin":"fha",
    "federal h admin":"fha",
    "fedl h admin":"fha",
    "fed h admin":"fha",
    "f h admin":"fha",
    "federal housing a":"fha",
    "fedl housing a":"fha",
    "fed housing a":"fha",
    "f housing a":"fha",
    "federal h a":"fha",
    "fedl h a":"fha",
    "fed h a":"fha",
    "f h a":"fha",

    # FEMA
    "federal emergency management agency":"fema",
    "fedl emergency management agency":"fema",
    "fed emergency management agency":"fema",
    "f emergency management agency":"fema",
    "federal em management agency":"fema",
    "fedl em management agency":"fema",
    "fed em management agency":"fema",
    "f em management agency":"fema",
    "federal e management agency":"fema",
    "fedl e management agency":"fema",
    "fed e management agency":"fema",
    "f e management agency":"fema",
    "federal emergency mgmt agency":"fema",
    "fedl emergency mgmt agency":"fema",
    "fed emergency mgmt agency":"fema",
    "f emergency mgmt agency":"fema",
    "federal em mgmt agency":"fema",
    "fedl em mgmt agency":"fema",
    "fed em mgmt agency":"fema",
    "f em mgmt agency":"fema",
    "federal e mgmt agency":"fema",
    "fedl e mgmt agency":"fema",
    "fed e mgmt agency":"fema",
    "f e mgmt agency":"fema",
    "federal emergency m agency":"fema",
    "fedl emergency m agency":"fema",
    "fed emergency m agency":"fema",
    "f emergency m agency":"fema",
    "federal em m agency":"fema",
    "fedl em m agency":"fema",
    "fed em m agency":"fema",
    "f em mgmt m":"fema",
    "federal e m agency":"fema",
    "fedl e m agency":"fema",
    "fed e m agency":"fema",
    "f e m agency":"fema",
    "federal emergency management ag":"fema",
    "fedl emergency management ag":"fema",
    "fed emergency management ag":"fema",
    "f emergency management ag":"fema",
    "federal em management ag":"fema",
    "fedl em management ag":"fema",
    "fed em management ag":"fema",
    "f em management ag":"fema",
    "federal e management ag":"fema",
    "fedl e management ag":"fema",
    "fed e management ag":"fema",
    "f e management ag":"fema",
    "federal emergency mgmt ag":"fema",
    "fedl emergency mgmt ag":"fema",
    "fed emergency mgmt ag":"fema",
    "f emergency mgmt ag":"fema",
    "federal em mgmt ag":"fema",
    "fedl em mgmt ag":"fema",
    "fed em mgmt ag":"fema",
    "f em mgmt ag":"fema",
    "federal e mgmt ag":"fema",
    "fedl e mgmt ag":"fema",
    "fed e mgmt ag":"fema",
    "f e mgmt ag":"fema",
    "federal emergency m ag":"fema",
    "fedl emergency m ag":"fema",
    "fed emergency m ag":"fema",
    "f emergency m ag":"fema",
    "federal em m ag":"fema",
    "fedl em m ag":"fema",
    "fed em m ag":"fema",
    "f em mgmt m":"fema",
    "federal e m ag":"fema",
    "fedl e m ag":"fema",
    "fed e m ag":"fema",
    "f e m ag":"fema",
    "federal emergency management a":"fema",
    "fedl emergency management a":"fema",
    "fed emergency management a":"fema",
    "f emergency management a":"fema",
    "federal em management a":"fema",
    "fedl em management a":"fema",
    "fed em management a":"fema",
    "f em management a":"fema",
    "federal e management a":"fema",
    "fedl e management a":"fema",
    "fed e management a":"fema",
    "f e management a":"fema",
    "federal emergency mgmt a":"fema",
    "fedl emergency mgmt a":"fema",
    "fed emergency mgmt a":"fema",
    "f emergency mgmt a":"fema",
    "federal em mgmt a":"fema",
    "fedl em mgmt a":"fema",
    "fed em mgmt a":"fema",
    "f em mgmt a":"fema",
    "federal e mgmt a":"fema",
    "fedl e mgmt a":"fema",
    "fed e mgmt a":"fema",
    "f e mgmt a":"fema",
    "federal emergency m a":"fema",
    "fedl emergency m a":"fema",
    "fed emergency m a":"fema",
    "f emergency m a":"fema",
    "federal em m a":"fema",
    "fedl em m a":"fema",
    "fed em m a":"fema",
    "f em mgmt m":"fema",
    "federal e m a":"fema",
    "fedl e m a":"fema",
    "fed e m a":"fema",
    "f e m a":"fema",

    # real estate board
    "real estate board":"reb",
    "re board":"reb",

    "eq":"equity",

    "mac":"mortgage corp",
    
    "mgmt":"management",
    "mngmnt":"management",
    "ass":"association",
    "assn":"association",
    "assns":"associations",
    "assoc":"associate",
    "assocs":"associates",
    "assocd":"associated",
    "grp":"group",
    "grps":"groups",
    "cmty":"community",
    "cmnty":"community",
    "jv":"joint venture",

    "ln":"lane",
    "rd":"road",
    "intst":"interstate",
    "allee":"alley",
    "ally":"alley",
    "aly":"alley",
    "anx":"annex",
    "anex":"annex",
    "annx":"annex",
    "arc":"arcade",
    "av":"avenue",
    "ave":"avenue",
    "aven":"avenue",
    "avenu":"avenue",
    "avnue":"avenue",
    "avn":"avenue",
    "bayoo":"bayou",
    "blf":"bluff",
    "bluf":"bluff",
    "blfs":"bluffs",
    "bot":"bottom",
    "btm":"bottom",
    "bottm":"bottom",
    "blvd":"boulevard",
    "boul":"boulevard",
    "boulv":"boulevard",
    "cen":"center",
    "centr":"center",
    "centre":"center",
    "cnter":"center",
    "cntr":"center",
    "ctr":"center",
    "cir":"circle",
    "circ":"circle",
    "circl":"circle",
    "crcl":"circle",
    "crcle":"circle",
    "cv":"cove",
    "crssng":"crossing",
    "crssing":"crossing",
    "xing":"crossing",
    "drv":"drive",
    "dr":"drive",
    "driv":"drive",
    "exp":"expressway",
    "expr":"expressway",
    "expw":"expressway",
    "expy":"expressway",
    "ext":"extension",
    "extn":"extension",
    "extnsn":"extension",
    "freewy":"freeway",
    "frway":"freeway",
    "frwy":"freeway",
    "fwy":"freeway",
    "gatewy":"gateway",
    "gatway":"gateway",
    "gtway":"gateway",
    "gtwy":"gateway",
    "grv":"grove",
    "harb":"harbor",
    "harbr":"harbor",
    "hbr":"harbor",
    "hrbor":"harbor",
    "hvn":"haven",
    "high way":"highway",
    "highwy":"highway",
    "hiway":"highway",
    "hiwy":"highway",
    "hway":"highway",
    "hwy":"highway",
    "jct":"junction",
    "jction":"junction",
    "jctn":"junction",
    "junctn":"junction",
    "juncton":"junction",
    "knl":"knoll",
    "lk":"lake",
    "lndg":"landing",
    "lndng":"landing",
    "mnr":"manor",
    "mdw":"meadow",
    "missn":"mission",
    "mssn":"mission",
    "mtwy":"motorway",
    "mt":"mount",
    "mnt":"mount",
    "mtn":"mountain",
    "mntain":"mountain",
    "mntn":"mountain",
    "mountin":"mountain",
    "mtin":"mountain",
    "prk":"park",
    "parkwy":"parkway",
    "pkway":"parkway",
    "pkwy":"parkway",
    "pky":"parkway",
    "plz":"plaza",
    "plza":"plaza",
    "prts":"ports",
    "radl":"radial",
    "rnch":"ranch",
    "rpd":"rapid",
    "rdg":"ridge",
    "rdge":"ridge",
    "rvr":"river",
    "rivr":"river",
    "riv":"river",
    "rds":"roads",
    "rte":"route",
    "shl":"shoal",
    "shrs":"shores",
    "skwy":"skyway",
    "sqre":"square",
    "sqr":"square",
    "sq":"square",
    "statn":"station",
    "stn":"station",
    "st":"street",
    "str":"street",
    "strt":"street",
    "trwy":"throughway",
    "smt":"summit",
    "trk":"track",
    "trfy":"trafficway",
    "trl":"trail",
    "trlr":"trailer",
    "tunnl":"tunnel",
    "tunl":"tunnel",
    "tpke":"turnpike",
    "trnpk":"turnpike",
    "turnpk":"turnpike",
    "vly":"valley",
    "vlly":"valley",
    "vw":"view",
    "vlg":"village",
    "villg":"village",
    "villiage":"village",
    "vl":"ville",
    "vst":"vista",
    "vsta":"vista",
    
    # states/mailing abbrevs (they should usually be okay though because the previous step in 
    # the standardization replaces a state abbrev if the state abbrev of the deeds being
    # processed is in the name. So would only mess things up if an out-of-state state abbrev
    # appears in the name and that out-of-state abbrev is ct or wy)
    "ct":"court",
    "wy":"way",
    # "st":"state" # or street [leaving this line out for now bc seems too dependent on other info so moving this replacement into the actual standardization function]

    "n":"north",
    "nw":"northwest",
    "n w":"northwest",
    "north west":"northwest",
    "ne":"northeast",
    "n e":"northeast",
    "north east":"northeast",
    "s":"south",
    "sw":"southwest",
    "s w":"southwest",
    "south west":"southwest",
    "se":"southeast",
    "s e":"southeast",
    "south east":"southeast",
    "e":"east",
    "w":"west",

    "bldg":"building",
    "apt":"apartment",
    "multifam":"multifamily",
    "multi-fam":"multifamily",
    "multi-family":"multifamily",
    "hm":"home",
    "ho":"homeowner",
    "hoa":"homeowners association",
    "ho assn":"homeowners association",
    "home assn":"homeowners association",
    "ho association":"homeowners association",
    "ha assn":"homeowners association",
    "ha association":"homeowners association",
    "svc":"service",
    "svcs":"services",
    "prop":"property",
    "props":"properties",
    "devlpr":"developer",
    "dvlpr":"developer",
    "dvlper":"developer",
    "dev":"development",
    "dvmnt":"development",
    "dvlmnt":"development",
    "dvlpmnt":"development",
    "dvlpment":"development",
    "devlpmnt":"develpment",
    "devlpment":"development",
    "devmnt":"development",
    "dvment":"development",
    "re":"real estate",
    "cre":"commercial real estate",
    "invs":"investments",
    "reit":"real estate investment trust",
    "re investment trust":"real estate investment trust",
    "re invs trust":"real estate investment trust",
    "bldr":"builder",
    "bldrs":"builders",
    "rlty":"realty",
    "rty":"realty",
    "titl":"title",
    "ag":"agricultural",
    "agr":"agricultural",
    "agri":"agricultural",
    "agric":"agricultural",

    "ctrl":"central",
    "cntrl":"central",
    "mt":"mount",
    "spgs":"springs",
    "auto":"automotive",

    "cnty":"county",
    "cty":"city",
    "am":"america",
    "us":"united states",
    "usa":"united states",
    "united states of america":"united states",
    "na":"north america", # ooh or national? (originally saw na in bank context referring to north america)
    "nat":"national",
    "natl":"national",
    "fed":"federal",
    "fedl":"federal",
    "agcy":"agency",

    "pmb":"private mailbox",
    "private mail box":"private mailbox",
    "condo":"condominium",
    "condos":"condominiums"
}


corporate_simplification_dict = {
    
    "corp":"",
    "corps":"",
    "inc":"",
    "co":"",
    "cos":"",
    "ltd":"",
    "llc":"",
    "lp":"",
    "llp":"",
    "holding":"",
    "fund":"",
    "funds":"",
    "holdings":"",
    "mutual":"",
    "bank":"",
    "trust":"",
    "branch":"",
    "subsidiary":"",

    "group":"",
    "association":"",
    "associate":"",
    "board":"",
    "organization":"",
    "collective":"",
    "cooperative":"",
    "business":"",
    "union":"",
    "government":"",
    "administration":"",
    "agency":"",
    "community":"",
    "joint venture":"",
    "developer":"",
    "development":"",
    "investor":"",
    "investment":"",

    # pluralize
    "groups":"",
    "associations":"",
    "associates":"",
    "boards":"",
    "organizations":"",
    "collectives":"",
    "cooperatives":"",
    "businesses":"",
    "unions":"",
    "governments":"",
    "administrations":"",
    "agencies":"",
    "communities":"",
    "joint ventures":"",
    "developers":"",
    "developments":"",
    "investors":"",
    "investments":"",

    "new york city":"nyc",
    "city of new york":"nyc",
    "city new york":"nyc",
    "san francisco":"sf",
    "sanfrancisco":"sf",
    "los angeles":"la",
    "losangeles":"la",
    "new orleans":"nola",
    "neworleans":"nola",
    "new orleans lousiana":"nola",
    "no la":"nola",
    "new orelans la":"nola",
    "city":"",
    "county":"",
    "state":"",
    "federal":"",
    "national":"",
    "na":"",
    "north america":"",
    "america":"",
    "united states":"",

    "and":"",
    "of":"",
    "a":"",
    "an":"",
    "for":"",
    "the":"",
    "at":"",
    "or":"",
    "as":"",
    "by":"",
    "to":"",
    "in":"",
    "out":"",
    "on":""

}

common_single_char_sequences_dict = {
    "n y c":"nyc",
    "n o l a":"nola",
    "no la":"nola",
    "n ola":"nola",
    "nol a":"nola",
    "l a":"la",
    "i n c":"inc",
    "c o r p":"corp",
    "c o":"co",
    "l l c":"llc",
    "ll c":"llc",
    "l lc":"llc",
    "l l p":"llp",
    "ll p":"llp",
    "l lp":"llp",
    "l t d":"ltd",
    "l td":"ltd",
    "lt d":"ltd",
    "f n m a":"fnma",
    "fnm a":"fnma",
    "f nma":"fnma",
    "fn ma":"fnma",
    "f nm a":"fnma",
    "f n ma":"fnma",
    "fn m a":"fnma",
    "g n m a":"gnma",
    "gnm a":"gnma",
    "g nma":"gnma",
    "gn ma":"gnma",
    "g nm a":"gnma",
    "g n ma":"gnma",
    "gn m a":"gnma",
    "g n m a":"gnma",
    "f n m a":"fnma",
    "f h l m c":"fhlmc",
    "fh l m c":"fhlmc",
    "f hl m c":"fhlmc",
    "f h lm c":"fhlmc",
    "f h l mc":"fhlmc",
    "fh lm c":"fhlmc",
    "fh l mc":"fhlmc",
    "f hl mc":"fhlmc",
    "fhl m c":"fhlmc",
    "fhl mc":"fhlmc",
    "f hlm c":"fhlmc",
    "f h lmc":"fhlmc",
    "fh lmc":"fhlmc",
    "fhlm c":"fhlmc",
    "f hlmc":"fhlmc",
    "f e d":"fed",
    "h o a":"hoa",
    "ho a":"hoa",
    "h oa":"hoa",
    "s v c s":'svcs',
    "s v c":"svc",
}

state_abbrev_to_state_dict = { 
    'al': 'alabama', 
    'ak': 'alaska', 
    'az': 'arizona', 
    'ar': 'arkansas', 
    'ca': 'california', 
    'co': 'colorado', 
    'ct': 'connecticut', 
    'de': 'delaware', 
    'fl': 'florida', 
    'ga': 'georgia', 
    'hi': 'hawaii', 
    'id': 'idaho', 
    'il': 'illinois', 
    'in': 'indiana', 
    'ia': 'iowa', 
    'ks': 'kansas', 
    'ky': 'kentucky', 
    'la': 'louisiana', 
    'me': 'maine', 
    'md': 'maryland', 
    'ma': 'massachusetts', 
    'mi': 'michigan', 
    'mn': 'minnesota', 
    'ms': 'mississippi', 
    'mo': 'missouri', 
    'mt': 'montana', 
    'ne': 'nebraska', 
    'nv': 'nevada', 
    'nh': 'new hampshire', 
    'nj': 'new jersey', 
    'nm': 'new mexico', 
    'ny': 'new york', 
    'nc': 'north carolina', 
    'nd': 'north dakota', 
    'oh': 'ohio', 
    'ok': 'oklahoma', 
    'or': 'oregon', 
    'pa': 'pennsylvania', 
    'ri': 'rhode island', 
    'sc': 'south carolina', 
    'sd': 'south dakota', 
    'tn': 'tennessee', 
    'tx': 'texas', 
    'ut': 'utah', 
    'vt': 'vermont', 
    'va': 'virginia', 
    'wa': 'washington', 
    'wv': 'west virginia', 
    'wi': 'wisconsin', 
    'wy': 'wyoming'
}

STR_TABLE = str.maketrans("","", string.punctuation)
and_regex = re.compile("&")
common_1char_seq_pattern = re.compile(r'\b(' + '|'.join(common_single_char_sequences_dict.keys()) + r')\b')
corporate_standardization_pattern = re.compile(r'\b(' + '|'.join(corporate_standardization_dict.keys()) + r')\b')
corporate_simplification_pattern = re.compile(r'\b(' + '|'.join(corporate_simplification_dict.keys()) + r')\b')
ordinal_num_re = re.compile(r"(\d)(?:st|nd|rd|th)\b")
govt_of_re = re.compile(r"(.*) \b(city of|county of|state of|government of|township of|municipality of|village of|cty of|cnty of|st of|govt of|muni of|vill of)$")
hyphen_re = re.compile(r"(\s)?-(\s)?")
st_abbrev_re = re.compile(r"\bst\b")
corporate_consolidate_single_characters_re = re.compile(r"\b(?:([a-z0-9])(?:\s|$)(?![a-z0-9][a-z0-9]))\b") # This is primarily meant to change things like n y c corporation into nyc corporation. Can look at the string "a d asd s f h asdfl123jk a f d falskdj s v s 1 2" for another example
lone_character_re = re.compile(r"(\s)?\b[a-z0-9]\b(\s)?")
deid_denum_regex = re.compile(r"\b((-|\s)*([a-z])?(-|\s)*([a-z])?(-|\s)*\d+(-|\s)*([a-z])?(-|\s)*([a-z])?(-|\s)*)*\b")
    # Go to python regex tester and input the below string to get a better feel for what the deid_denum_regex does:
    # ab-23
    # .
    # sf- - 233212a32 - 32 a -sa7 d-ads -12
    # .
    # f3b
    # .
    # ab- 23
    # .
    # sss3
    # .
    # asdf 3 sdf
    # .
    # all west 23 group 10
    # .
state_abbrev_re_dict = {}
for state_abbrev in state_abbrev_to_state_dict:
    state_abbrev_re = re.compile("\b(" + state_abbrev + "|" + state_abbrev[0] + " " + state_abbrev[1] + ")\b")
    state_abbrev_re_dict[state_abbrev] = state_abbrev_re
